"use strict";
exports.__esModule = true;
exports.Keys = void 0;
var Keys;
(function (Keys) {
    Keys["ID"] = "id";
    Keys["CREATED"] = "created";
    Keys["MODIFIED"] = "modified";
    Keys["DESCRIPTION"] = "description";
    Keys["TITLE"] = "title";
    Keys["URL"] = "url";
    Keys["TITLE_TYPE"] = "titleType";
    Keys["RATING"] = "rating";
    Keys["RUNTIME"] = "runtime";
    Keys["YEAR"] = "year";
    Keys["GENRES"] = "genres";
    Keys["NUM_VOTES"] = "numVotes";
    Keys["RELEASE_DATE"] = "releaseDate";
    Keys["DIRECTORS"] = "directors";
    Keys["YOUR_RATING"] = "rated";
    Keys["POSITION"] = "order";
    Keys["DATE_RATED"] = "dateRated";
})(Keys = exports.Keys || (exports.Keys = {}));
